version: '3.8'
services:
  db-produtos:
    image: postgres:latest
    networks:
      - network-produtos
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: produtos
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
        - "5433:5432"
  cmp-produtos:
    build: .
    image: entityblackhawk/cmp-produtos:latest
    environment:
        DATABASE_HOST_PORT: db-produtos:5432
    networks:
        - network-produtos
    ports:
      - "8081:8080"
    depends_on:
        - db-produtos

networks:
    network-produtos:
        driver: bridge