version: '3.8'
services:
  db_produtos:
    image: postgres:latest
    networks:
      - network_produtos
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: produtos
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
        - "5433:5432"
  cmp_produtos:
    build: .
    image: entityblackhawk/cmp-produtos:latest
    networks:
        - network_produtos
    ports:
      - "8081:8080"
    depends_on:
        - db_produtos

networks:
    network_produtos:
        driver: bridge