version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: produtos
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
        - "5433:5432"
  cmp_vendas:
    build: .
    image: entityblackhawk/cmp-produtos:latest
    ports:
      - "8081:8081"
    depends_on:
        - postgres